### ISSUE TITLE
Ошибка с примером.

### ISSUE THREAD

**Issue by greyghost1979** [ai-forever/gigachain#60]
### Информация об окружении

Windows 10, Python 3.10.9, текущая версия GigaChain

### К кому обратиться?

@Rai220 Konstantin Krestnikov
Добрый день !
Помогите пожалуйста, пытаюсь выполнить Ваш пример:
`from langchain.chat_models.gigachat import GigaChat
llm = GigaChat(credentials="BLABLABLA==")
from langchain.schema import HumanMessage
question = "Какой плащ был у Понтия Пилата?"
llm([HumanMessage(content=question)]).content[0:200]
from langchain.document_loaders import TextLoader
from langchain.text_splitter import (
    CharacterTextSplitter,
    RecursiveCharacterTextSplitter,
)
loader = TextLoader("мастер_и_маргарита.txt")
documents = loader.load()
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
)
documents = text_splitter.split_documents(documents)
print(f"Total documents: {len(documents)}")
from langchain.vectorstores import Chroma
from langchain_community.embeddings import GigaChatEmbeddings
embeddings = GigaChatEmbeddings(one_by_one_mode=True, _debug_delay=0.005)
from chromadb.config import Settings
from langchain.vectorstores import Chroma
db = Chroma.from_documents(
    documents,
    embeddings,
    client_settings=Settings(anonymized_telemetry=False),
)
docs = db.similarity_search(question, k=4)
len(docs)
print(f"... {str(docs[0])[620:800]} ...")
from langchain.chains import RetrievalQA
qa_chain = RetrievalQA.from_chain_type(llm, retriever=db.as_retriever())
qa_chain({"query": question})
`
И получаю ошибку:
`Profanity field is deprecated. Use 'profanity_check' instead.
Total documents: 1
Traceback (most recent call last):
  File "F:\Work\Giga\Gigatest_01.py", line 33, in <module>
    db = Chroma.from_documents(
  File "C:\Python3_10_9\lib\site-packages\langchain_community\vectorstores\chroma.py", line 771, in from_documents
    return cls.from_texts(
  File "C:\Python3_10_9\lib\site-packages\langchain_community\vectorstores\chroma.py", line 729, in from_texts
    chroma_collection.add_texts(
  File "C:\Python3_10_9\lib\site-packages\langchain_community\vectorstores\chroma.py", line 275, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
  File "C:\Python3_10_9\lib\site-packages\langchain_community\embeddings\gigachat.py", line 124, in embed_documents
    for embedding in self._client.embeddings(texts=[text], model=model).data:
  File "C:\Python3_10_9\lib\site-packages\gigachat\client.py", line 214, in embeddings
    return self._decorator(
  File "C:\Python3_10_9\lib\site-packages\gigachat\client.py", line 202, in _decorator
    return call()
  File "C:\Python3_10_9\lib\site-packages\gigachat\client.py", line 215, in <lambda>
    lambda: post_embeddings.sync(self._client, access_token=self.token, input_=texts, model=model)
  File "C:\Python3_10_9\lib\site-packages\gigachat\api\post_embeddings.py", line 71, in sync
    return _build_response(response)
  File "C:\Python3_10_9\lib\site-packages\gigachat\api\post_embeddings.py", line 57, in _build_response
    raise AuthenticationError(response.url, response.status_code, response.content, response.headers)
gigachat.exceptions.AuthenticationError: (URL('https://gigachat.devices.sberbank.ru/api/v1/embeddings'), 401, b'{"status":401,"message":"Unauthorized"}\n', Headers([('server', 'nginx'), ('date', 'Sat, 13 Jan 2024 20:10:08 GMT'), ('content-type', 'application/json; charset=utf-8'), ('content-length', '40'), ('connection', 'keep-alive'), ('x-request-id', '52c28f4b-9f96-4e09-a610-181e59e16fa0'), ('x-session-id', '0c1e6a1f-6363-408f-9d5d-b78e799d0a81'), ('allow', 'GET, POST'), ('strict-transport-security', 'max-age=31536000; includeSubDomains'), ('allow', 'GET, POST'), ('strict-transport-security', 'max-age=31536000; includeSubDomains')]))`

Вот не понимаю, что не так - всё как у Вас, токен рабочий,
Если с ним же запускать код:
`
from langchain.schema import HumanMessage, SystemMessage
from langchain.chat_models.gigachat import GigaChat
chat = GigaChat(credentials=GigaChat(credentials="BLABLABLA==")
messages = [
    SystemMessage(
        content="Ты эмпатичный бот-психолог, который помогает пользователю решить его проблемы."
    )
]
while(True):
    user_input = input("User: ")
    messages.append(HumanMessage(content=user_input))
    res = chat(messages)
    messages.append(res)
    print("Bot: ", res.content)`
    То всё работает - прошу хоть какой-то помощи.

### Дополнительная информация

- [X] Официальных примеров (*notebooks*)/скриптов
- [ ] Собственных или доработанных скриптов

### Компоненты

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Воспроизведение ошибки

from langchain.chat_models.gigachat import GigaChat
llm = GigaChat(credentials="ZWMwYmQwNDctZTdiYi00OTY4LTk5ODktNDZmMmQ2ZDAxYTk5OjgzNTgzMTk0LTEyN2QtNDE1ZS05ZTRiLTdlZmI0NTg0NTZiMA==")
from langchain.schema import HumanMessage
question = "Какой плащ был у Понтия Пилата?"
llm([HumanMessage(content=question)]).content[0:200]
from langchain.document_loaders import TextLoader
from langchain.text_splitter import (
    CharacterTextSplitter,
    RecursiveCharacterTextSplitter,
)
loader = TextLoader("мастер_и_маргарита.txt")
documents = loader.load()
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
)
documents = text_splitter.split_documents(documents)
print(f"Total documents: {len(documents)}")
from langchain.vectorstores import Chroma
from langchain_community.embeddings import GigaChatEmbeddings
embeddings = GigaChatEmbeddings(one_by_one_mode=True, _debug_delay=0.005)
from chromadb.config import Settings
from langchain.vectorstores import Chroma
db = Chroma.from_documents(
    documents,
    embeddings,
    client_settings=Settings(anonymized_telemetry=False),
)
docs = db.similarity_search(question, k=4)
len(docs)
print(f"... {str(docs[0])[620:800]} ...")
from langchain.chains import RetrievalQA
qa_chain = RetrievalQA.from_chain_type(llm, retriever=db.as_retriever())
qa_chain({"query": question})

### Ожидаемое поведение

Ожидал ответ на вопрос. Но почему то ошибка авторизации

**Comment by Rai220** [comment]
Добрый день!
Спасибо за замечание, действительно в примере ошибка, нужно добавить credentials=... в GigaChatEmbeddings(...)
Поправим!

**Comment by Rai220** [comment]
Добрый день!
Спасибо за замечание, действительно в примере ошибка, нужно добавить credentials=... в GigaChatEmbeddings(...)
Поправим!

**Comment by greyghost1979** [comment]
С Ричи тоже не авторизуется. Или это потому что у меня прока фри -тариф ?

пн, 15 янв. 2024 г., 13:50 Konstantin Krestnikov ***@***.***>:
