### ISSUE TITLE
Unicode decode error при импорте from langchain.agents

### ISSUE THREAD

**Issue by hookenful** [ai-forever/gigachain#80]
Пытаюсь импортировать любую вещь из  `langchain.agents` и получаю такую ошибку. В чем может быть причина? 
 
```
Process SpawnProcess-5:
Traceback (most recent call last):
  File "C:\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\uvicorn\_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\uvicorn\config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\api\main.py", line 15, in <module>
    from chat import ask_question, getChatHistory
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\api\chat.py", line 11, in <module>
    from langchain.agents import Agent
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\langchain\agents\__init__.py", line 44, in <module>
    from langchain.agents.agent import (
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\langchain\agents\agent.py", line 50, in <module>
    from langchain.chains.base import Chain
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\langchain\chains\__init__.py", line 53, in <module>
    from langchain.chains.llm_summarization_checker.base import LLMSummarizationCheckerChain
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\langchain\chains\llm_summarization_checker\base.py", line 22, in <module>
    REVISED_SUMMARY_PROMPT = PromptTemplate.from_file(PROMPTS_DIR / "revise_summary.txt")
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\langchain_core\prompts\prompt.py", line 205, in from_file
    template = f.read()
               ^^^^^^^^
  File "C:\Python311\Lib\encodings\cp1251.py", line 24, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 459: character maps to <undefined>

```

**Comment by hookenful** [comment]
Вроде починил. Включил в Windows по умолчанию UTF-8 кодировку. Сейчас другая ошибка

```
Traceback (most recent call last):
  File "C:\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\uvicorn\_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\uvicorn\config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\api\main.py", line 15, in <module>
    from chat import ask_question, getChatHistory
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\api\chat.py", line 11, in <module>
    from langchain.agents import Agent
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\langchain\agents\__init__.py", line 60, in <module>
    from langchain.agents.gigachat_functions_agent.base import (
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\langchain\agents\gigachat_functions_agent\base.py", line 4, in <module>
    from langchain_community.tools.render import format_tool_to_gigachat_function
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\langchain_community\tools\render.py", line 9, in <module>
    from langchain_community.utils.gigachat_functions import (
  File "C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\langchain_community\utils\gigachat_functions.py", line 3, in <module>
    from langchain_core.utils.function_calling import (
ImportError: cannot import name 'convert_pydantic_to_gigachat_function' from 'langchain_core.utils.function_calling' (C:\Users\hooki\Documents\coffeeface\src\ai-chat\.venv\Lib\site-packages\langchain_core\utils\function_calling.py)

```

Насколько я вижу в `langchain_core\utils\function_calling.py` нет и не может быть функции `convert_pydantic_to_gigachat_function`

**Comment by Rai220** [comment]
Добрый день. Попробуйте обновиться до самой последней версии gigachain и связаных библиотек.

**Comment by hookenful** [comment]
> Добрый день. Попробуйте обновиться до самой последней версии gigachain и связаных библиотек.

Спасибо, получилось! 
Ещё заметил, что в зависимостях была библиотека langchain-core. Убрал, обновил gigachain через ключ -U и получилось
